In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from yellowbrick.classifier import ConfusionMatrix

In [3]:
credito = pd.read_csv('../data/Credit.csv')
credito.shape

(1000, 21)

In [4]:
credito.head()

  checking_status  duration  ... foreign_worker class
0              <0         6  ...            yes  good
1        0<=X<200        48  ...            yes   bad
2   'no checking'        12  ...            yes  good
3              <0        42  ...            yes  good
4              <0        24  ...            yes   bad

[5 rows x 21 columns]

In [7]:
# Formato de matriz
previsores = credito.iloc[:,0:20].values
classe = credito.iloc[:,20].values

In [8]:
# Transformando atributos categóricos em numéricos passando o índice de cada coluna categórica.
# Criando um objeto para cada atributo categórico, pois em sequência irei o processo de encoding novamente para o registro de testes.

labelEncoder1 = LabelEncoder()
previsores[:,0] = labelEncoder1.fit_transform(previsores[:,0])

labelEncoder2 = LabelEncoder()
previsores[:,2] = labelEncoder1.fit_transform(previsores[:,2])

labelEncoder3 = LabelEncoder()
previsores[:,3] = labelEncoder1.fit_transform(previsores[:,3])

labelEncoder4 = LabelEncoder()
previsores[:,5] = labelEncoder1.fit_transform(previsores[:,5])

labelEncoder5 = LabelEncoder()
previsores[:,6] = labelEncoder1.fit_transform(previsores[:,6])

labelEncoder6 = LabelEncoder()
previsores[:,8] = labelEncoder1.fit_transform(previsores[:,8])

labelEncoder7 = LabelEncoder()
previsores[:,9] = labelEncoder1.fit_transform(previsores[:,9])

labelEncoder8 = LabelEncoder()
previsores[:,11] = labelEncoder1.fit_transform(previsores[:,11])

labelEncoder9 = LabelEncoder()
previsores[:,13] = labelEncoder1.fit_transform(previsores[:,13])

labelEncoder10 = LabelEncoder()
previsores[:,14] = labelEncoder1.fit_transform(previsores[:,14])

labelEncoder11 = LabelEncoder()
previsores[:,16] = labelEncoder1.fit_transform(previsores[:,16])

labelEncoder12 = LabelEncoder()
previsores[:,18] = labelEncoder1.fit_transform(previsores[:,18])

labelEncoder13 = LabelEncoder()
previsores[:,19] = labelEncoder1.fit_transform(previsores[:,19])

In [9]:
X_treinamente, X_teste, y_treinamento, y_teste = train_test_split(previsores,
                                                                  classe,
                                                                  test_size=0.3,
                                                                  random_state=0)
X_teste

array([[2, 36, 3, ..., 1, 1, 1],
       [0, 9, 3, ..., 2, 0, 0],
       [0, 18, 3, ..., 1, 1, 1],
       ...,
       [0, 24, 1, ..., 1, 0, 1],
       [1, 27, 4, ..., 1, 1, 1],
       [1, 12, 3, ..., 1, 0, 1]], dtype=object)